title:            Intellectual Hedonism
tagline:          Consumption for recreation
description: "Let us celebrate the ever increasing entropy by consuming random information. This blog is a collection of vials of dopamine. This is my cure for boredom. It can be yours too."
# An awesome quote for your website
quote:  "The only way to get rid of temptation is to yield to it. Resist it, and your soul grows sick with longing for the things it has forbidden to itself."
canonical: intellectual-hedonism.github.io
#Comment out the below line when pushing to gh-pages
#url: http://10.42.0.1/_site 
#For local development only. Comment it out.
#file_end: .html
#url: http://localhost:4000

# Owner/author information
owner:
  name:           Suriyadeepan Ramamoorthy
  avatar:         avatar.jpg
  bio:            
  email:          suriyadeepan.r@gmail.com
  twitter:        
  github:         intellectual-hedonism
  instagram:      
  dribbble:
  googleplus:     
  disqus:         suriyadeepan
  location:       
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
